import {cell} from '../redux/gameSlice'
export const FirstLevel: cell[] = [
    {position: 0, status: 'character'},
    {position: 1, status: 'empty'},
    {position: 2, status: 'empty'},
    {position: 3, status: 'empty'},
    {position: 4, status: 'block'},
    {position: 5, status: 'block'},
    {position: 6, status: 'block'},
    {position: 7, status: 'empty'},
    {position: 8, status: 'loot'},
    {position: 9, status: 'empty'},
    {position: 10, status: 'empty'},
    {position: 11, status: 'block'},
    {position: 12, status: 'block'},
    {position: 13, status: 'block'},
    {position: 14, status: 'block'},
    {position: 15, status: 'block'},
]
export const SecondLevel: cell[] = [
    {position: 0, status: 'character'},
    {position: 1, status: 'empty'},
    {position: 2, status: 'empty'},
    {position: 3, status: 'empty'},
    {position: 4, status: 'block'},
    {position: 5, status: 'block'},
    {position: 6, status: 'block'},
    {position: 7, status: 'empty'},
    {position: 8, status: 'empty'},
    {position: 9, status: 'block'},
    {position: 10, status: 'loot'},
    {position: 11, status: 'block'},
    {position: 12, status: 'empty'},
    {position: 13, status: 'empty'},
    {position: 14, status: 'empty'},
    {position: 15, status: 'block'},
]
export const ThirdLevel: cell[] = [
    {position: 0, status: 'loot'},
    {position: 1, status: 'empty'},
    {position: 2, status: 'empty'},
    {position: 3, status: 'empty'},
    {position: 4, status: 'block'},
    {position: 5, status: 'block'},
    {position: 6, status: 'block'},
    {position: 7, status: 'empty'},
    {position: 8, status: 'empty'},
    {position: 9, status: 'block'},
    {position: 10, status: 'block'},
    {position: 11, status: 'block'},
    {position: 12, status: 'character'},
    {position: 13, status: 'empty'},
    {position: 14, status: 'empty'},
    {position: 15, status: 'empty'},
]